name: "terraform preview"

on:
  push:
    branches:
      - main
    path:
      - .github/workflows/**
      - "**/*.yaml"

permissions:
  id-token: write
  contents: read

env: 
  NGINX_VERSION: 1.23.3

jobs:
  preview:
    name: "Preview"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}

      - name: Set image tag
        run: |
          cd kustomize/overlays/production
          kustomize edit set image nginx:$NGINX_VERSION
          cat kustomization.yaml
      
       - name: Push changes
         uses: ad-m/github-push-action@master
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           branch: main