name: "terraform preview"

on:
  push:
    branches:
      - main
    path:
      - .github/workflows/**
      - "**/*.yaml"

permissions:
  id-token: write
  contents: read

jobs:
  preview:
    name: "Preview"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set image tag
        run: |
          cd kustomize/overlays/production
          kustomize edit set image nginx:1.23.3
          cat kustomization.yaml