name: "terraform preview"

on:
  push:
    branches:
      - main
    path:
      - .github/workflows/**
      - "**/*.yaml"

permissions:
  id-token: write
  contents: read

env: 
  NGINX_VERSION: 1.23.3

jobs:
  preview:
    name: "Preview"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set image tag
        run: |
          cd kustomize/overlays/production
          kustomize edit set image nginx:$NGINX_VERSION
          cat kustomization.yaml
      
      - name: Configure & Git push kustomization
        run: |
          git config --global user.email ${{ secrets.EMAIL}}
          git config --global user.name ${{ secrets.NAME}}
          git add .
          git commit -m "nginx:$NGINX_VERSION"
          git push 